return {
  {
    "Mofiqul/vscode.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      local c = require("vscode.colors").get_colors()
      require("vscode").setup({
        style = "dark",
        transparent = false,
        italic_comments = true,
        -- stronger dark+ look
        group_overrides = {
          Comment = { fg = "#6A9955", italic = true },
          Keyword = { fg = "#C586C0" },
          Function = { fg = "#DCDCAA" },
          String = { fg = "#CE9178" },
          Number = { fg = "#B5CEA8" },
          Type = { fg = "#4EC9B0" },
          Constant = { fg = "#9CDCFE" },
          Identifier = { fg = "#9CDCFE" },
          LspReferenceText = { bg = "#2A2D2E", underline = false },
          LspReferenceRead = { bg = "#2A2D2E", underline = false },
          LspReferenceWrite = { bg = "#3A2F2F", underline = false },
          ["@function"] = { fg = "#DCDCAA" },
          ["@function.call"] = { fg = "#DCDCAA" },
          ["@function.builtin"] = { fg = "#DCDCAA" },
          ["@keyword"] = { fg = "#C586C0" },
          ["@string"] = { fg = "#CE9178" },
          ["@type"] = { fg = "#4EC9B0" },
          ["@number"] = { fg = "#B5CEA8" },
          ["@constant"] = { fg = "#9CDCFE" },
          ["@variable"] = { fg = "#9CDCFE" },
          ["@variable.parameter"] = { fg = "#9CDCFE" },
          ["@variable.member"] = { fg = "#9CDCFE" },
          ["@property"] = { fg = "#9CDCFE" },
          ["@field"] = { fg = "#9CDCFE" },
          -- Go treesitter tokens
          ["@variable.member"] = { fg = "#9CDCFE" },
          ["@function.method"] = { fg = "#DCDCAA" },
          ["@function.method.call"] = { fg = "#DCDCAA" },
          ["@type.builtin"] = { fg = "#4EC9B0" },
          ["@constant.builtin"] = { fg = "#569CD6" },
          ["@keyword.return"] = { fg = "#C586C0" },
          ["@keyword.function"] = { fg = "#C586C0" },
          ["@module"] = { fg = "#4EC9B0" },
          ["@label"] = { fg = "#C8C8C8" },
          -- gopls semantic tokens (override treesitter for Go)
          ["@lsp.type.function"] = { fg = "#DCDCAA" },
          ["@lsp.type.method"] = { fg = "#DCDCAA" },
          ["@lsp.type.variable"] = { fg = "#9CDCFE" },
          ["@lsp.type.parameter"] = { fg = "#9CDCFE" },
          ["@lsp.type.property"] = { fg = "#9CDCFE" },
          ["@lsp.type.type"] = { fg = "#4EC9B0" },
          ["@lsp.type.typeParameter"] = { fg = "#4EC9B0" },
          ["@lsp.type.interface"] = { fg = "#4EC9B0" },
          ["@lsp.type.namespace"] = { fg = "#4EC9B0" },
          ["@lsp.type.keyword"] = { fg = "#C586C0" },
          ["@lsp.mod.defaultLibrary"] = { fg = "#DCDCAA" },
          ["@lsp.mod.readonly"] = { fg = "#9CDCFE" },
          ["@lsp.typemod.function.defaultLibrary"] = { fg = "#DCDCAA" },
          ["@lsp.typemod.variable.readonly"] = { fg = "#9CDCFE" },
          ["@lsp.typemod.parameter.readonly"] = { fg = "#9CDCFE" },
          ["@lsp.type.function.go"] = { fg = "#DCDCAA" },
          ["@lsp.type.method.go"] = { fg = "#DCDCAA" },
          ["@lsp.type.variable.go"] = { fg = "#9CDCFE" },
          ["@lsp.type.parameter.go"] = { fg = "#9CDCFE" },
          ["@lsp.type.property.go"] = { fg = "#9CDCFE" },
          ["@lsp.type.namespace.go"] = { fg = "#4EC9B0" },
          ["@lsp.type.struct.go"] = { fg = "#4EC9B0" },
          ["@lsp.type.type.go"] = { fg = "#4EC9B0" },
          ["@lsp.type.typeParameter.go"] = { fg = "#4EC9B0" },
          ["@lsp.type.interface.go"] = { fg = "#4EC9B0" },
          ["@lsp.type.keyword.go"] = { fg = "#C586C0" },
          ["@lsp.typemod.function.defaultLibrary.go"] = { fg = "#DCDCAA" },
          ["@lsp.typemod.variable.readonly.go"] = { fg = "#9CDCFE" },
          ["@lsp.typemod.variable.globalScope.go"] = { fg = "#9CDCFE" },
          ["@lsp.typemod.variable.fileScope.go"] = { fg = "#9CDCFE" },
          ["@lsp.typemod.parameter.readonly.go"] = { fg = "#9CDCFE" },
        },
      })
      require("vscode").load()
      vim.api.nvim_set_hl(0, "LspReferenceText", { fg = "NONE", bg = "#2A2D2E", underline = false })
      vim.api.nvim_set_hl(0, "LspReferenceRead", { fg = "NONE", bg = "#2A2D2E", underline = false })
      vim.api.nvim_set_hl(0, "LspReferenceWrite", { fg = "NONE", bg = "#3A2F2F", underline = false })
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = { colorscheme = "vscode" },
  },
}
